on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - run: gci -recur -hid C:\Users\runneradmin\.cargo
      - run: gci -recur -hid C:\Users\Default\.cargo
      - run: rustup update
